### ISSUE TITLE
Add support for setting path

### ISSUE THREAD

**Issue by nickbasham** [cferdinandi/jar#1]
Unless specified, browsers will set a cookie's path to the current relative path. It would be great to either set the default path to root and/or allow the ability to set the path.

**Comment by cferdinandi** [comment]
This is probably overdone, but I just pushed a major version bump (now v1.x), that defaults to the root path, and supports an object of cookie options. Documentation updated to match.

**Comment by nickbasham-grayloon** [comment]
Awesome, thanks, Chris!
